version: "3"
services:
  nginx-forwarder:
    build: ./nginx-forwarder
    image: nginx-forwarder
  app-in-compose:
    image: shrektan/r-production
    ports:
      - 3838:3838
    volumes:
      - "./apps/test2:/app"
    command: ['Rscript', '-e', "shiny::runApp('/app', host = '0.0.0.0', port = 3838)"]
  shinyproxy:
    build: ./shinyproxy
    ports:
      - 8080:8080
    environment: 
      - "WORK_DIR=${PWD}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./shinyproxy-logs/server:/log"
      - "./shinyproxy-logs/container:/container-logs"
      - "./shinyproxy:/opt/shinyproxy"
