proxy:
  title: ShinyProxy
  port: 8080
  #logo-url: file:///opt/shinyproxy/logo.png
  template-path: ./templates
  container-log-path: /container-logs
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
  hide-navbar: false
  docker:
    internal-networking: true
    container-network: "shinyproxy-docker-compose-example_default"
  specs:
  - id: app-normal
    container-cmd: ["R", "-e", "shiny::runApp('/apps/test', host = '0.0.0.0', port = 3838)"]
    container-image: shrektan/r-production
    container-network: "${proxy.docker.container-network}"
    container-volumes: ["${WORK_DIR}/apps:/apps"]
  - id: app-not-in-compose
    container-cmd: ["R", "-e", "shiny::runApp('/apps/test2', host = '0.0.0.0', port = 3838)"]
    container-image: shrektan/r-production
    container-network: "${proxy.docker.container-network}"
    container-volumes: ["${WORK_DIR}/apps:/apps"]    
  - id: app-in-compose
    container-image: nginx-forwarder
    container-network: "${proxy.docker.container-network}"
    container-env:
      APP_NAME: app-in-compose
logging:
  file:
    /log/shinyproxy.log

server:
  servlet:
    context-path:  /
